name: smca_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  fluttertoast: ^8.2.2
  firebase_core: ^2.26.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.4.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^5.0.0+4
  provider: ^6.0.1
  percent_indicator: ^4.2.3
  google_fonts: 6.1.0
  shared_preferences: ^2.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_messaging: ^14.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_launcher.png"
  adaptive_icon_background: "assets/img/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/